

services:
  db:
    build:
      context: ./compose/db/
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_app

  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 500mb --appendonly yes --notify-keyspace-events A
    volumes:
      -  redis_data:/data
    networks:
      -  backend_app

  web:
    image: python:3.12-slim
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    env_file:
      - .env
    restart: always
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static_collect:/app/static_collect
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend_app
      - backend_proxy
    environment:
      DJANGO_ENV: "local"
      DJANGO_SETTINGS_MODULE: config.settings
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
      DJANGO_ADMIN_PASSWORD: ${DJANGO_ADMIN_PASSWORD}
      DB_HOST: db
  
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_collect:/app/static_collect
      - ./media:/app/media
      - ./certs:/etc/letsencrypt
      - ./certbot_data:/var/www/certbot
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_proxy  
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
     - ./certs:/etc/letsencrypt
     - ./certbot_data:/var/www/certbot
     - ./html:/usr/share/nginx/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - backend_proxy

volumes:
    redis_data:
    pg_data:
    certbot_certs: 
  
networks:
  backend_proxy:
    driver: bridge
  backend_app:
    driver: bridge


