

services:
  db:
    build:
      context: .
      dockerfile: dockerfile.pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      ports: "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - network

  redis:
    image: redis:alpine
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_MAXMEMORY: 500mb
      REDIS_AOF_ENABLED: yes
      REDIS_NOTIFY_KEYSPACE_EVENTS: A
    ports: 
      -  "6379:6379"
    volumes:
      -  redis_data:/data
    networks:
      -  network

  web:
    build: .
    env_file:
      - .env
    command: bash -c "sleep 10 && gunicorn project.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app  # Монтируем текущую директорию в контейнер
    ports: 
      -  8000:8000
    depends_on:
      - db
      - redis
    networks:
      - network
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE} 
      DB_HOST: db 

volumes:
    redis_data:
    pg_data: 
networks:
    network:


