

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend_app
    command: >
      sh -c "apk update && apk upgrade && apk add --no-cache gcc libpq-dev postgresql-client && exec docker-entrypoint.sh postgres"

  redis:
    image: redis:alpine
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_MAXMEMORY: 500mb
      REDIS_AOF_ENABLED: yes
      REDIS_NOTIFY_KEYSPACE_EVENTS: A
    ports: 
      -  "6379:6379"
    volumes:
      -  redis_data:/data
    networks:
      -  backend_app

  web:
    image: python:3.12-slim
    build:
      dockerfile: dockerfile
    env_file:
      - .env
    restart: always
    command: poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend_app
      - backend_proxy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production

      DB_HOST: db
  
  nginx:
    image: nginx:latest
    container_name: nginx_server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_collect:/app/static_collect
      - ./media:/app/media
      - ./certs:/etc/letsencrypt
      - ./certbot_data:/var/www/certbot
      - ./html:/usr/share/nginx/html
   
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_proxy  
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
     - ./certs:/etc/letsencrypt
     - ./certbot_data:/var/www/certbot
     - ./html:/usr/share/nginx/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;"
    networks:
      - backend_proxy

volumes:
    redis_data:
    pg_data:
    certbot_certs: 
networks:
  backend_proxy:
    driver: bridge
  backend_app:
    driver: bridge


